version: "3.4"
services:
  linting:
    container_name: linting
    build:
      context: .
      target: linting
      dockerfile: Dockerfile
    volumes:
      - .:/app

  tests_unit:
    container_name: tests_unit
    build:
      context: .
      target: tests_unit
      dockerfile: Dockerfile
    volumes:
      - .:/app

  tests_e2e:
    container_name: tests_e2e
    build:
      context: .
      target: tests_e2e
      dockerfile: Dockerfile
    volumes:
      - .:/app

  dev:
    container_name: dev
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4200:80"
